name = "Catppuccin Mocha"
bg = "#11111b"
fg = "#cdd6f4"
border = "Rounded"
border_color = "#6e738d"
border_focused_color = "#cba6f7"
hl_bg = "#6e738d"
solid_bg = "#a6e3a1"
solid_fg = "#181926"
trusted = "#a6e3a1"
remake = "#f38ba8"